apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: {{ .Values.ollama.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: {{ .Values.ollama.image | quote }}
          imagePullPolicy: {{ .Values.ollama.imagePullPolicy | quote }}
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
          # Simple liveness check
          livenessProbe:
            exec:
              command: ["ollama", "--version"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama-pvc

