apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  labels:
    app: open-webui
spec:
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 8080
  type: LoadBalancer

