apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: {{ .Values.openwebui.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: {{ .Values.openwebui.image | quote }}
          imagePullPolicy: {{ .Values.openwebui.imagePullPolicy | quote }}
          ports:
            - containerPort: 8080
          env:
            # This points Open WebUI at Ollama's internal service DNS
            - name: OLLAMA_API_URL
              value: "http://ollama-service:11434"
          volumeMounts:
            - name: open-webui-storage
              mountPath: /app/backend/data
      volumes:
        - name: open-webui-storage
          persistentVolumeClaim:
            claimName: open-webui-pvc

